### ISSUE TITLE
Example in readme improvement

### ISSUE THREAD

**Issue by ndelangen** [marten-de-vries/kneden#102]
Maybe, I have a feeling I'm missing misunderstanding something, but it would seem to me the example in the readme is incorrect?

## Example

**In**

```js
async function test() {
  await db.destroy();
}
```

**Out**

```js
function test() {
  return Promise.resolve().then(function () {
    return db.destroy();
  }).then(function () {});
}
```

These 2 functions behave differently: the first returns undefined, the second returns a promise?

---

Perhaps a better example would be:

**In**

```js
async function test() {
  const result = await db.destroy();
  return result.ok;
}
```

**Out**

```js
function test() {
  return Promise.resolve().then(function () {
    return db.destroy();
  }).then(function (result) {
    return result.ok;
  });
}
```

Does it work like that?

**Comment by danharper** [comment]
```js
async function test() {
  await db.destroy();
}
```

actually returns a Promise (of undefined) - any `async` function returns a Promise.

![image](https://cloud.githubusercontent.com/assets/510740/22253227/a81ac974-e248-11e6-9b64-1d559bbed4f0.png)
