### ISSUE TITLE
Why does awaiting resolve a new Promise?

### ISSUE THREAD

**Issue by AprilArcus** [marten-de-vries/kneden#25]
Currently,

```JavaScript
async function test() {
  await db.destroy();
}
```

transpiles to

```JavaScript
function test() {
  return Promise.resolve().then(function () {
    return db.destroy();
  }).then(function () {});
}
```

instead of

```JavaScript
function test() {
  return db.destroy().then(function () {});
}
```

Why is this? We know the expression to the right of `await` must be a Promise, so this seems overcautious.

**Comment by ljharb** [comment]
*You* might know that, but the *program* can't know that - it might be a Promise, or a generic thenable, or a normal value. By spec, anything `await`ed must be coerced into a native Promise, whether it is one or not.

**Comment by AprilArcus** [comment]
Thanks for the clarification! I was not aware that plain values were legal in that position.

What about

```JavaScript
function test() {
  return Promise.resolve(db.destroy).then(function () {});
}
```

?

**Comment by ljharb** [comment]
@AprilArcus that would make a promise for the `db.destroy` function - and if you did `Promise.resolve(db.destroy())` then that would a) run synchronously instead of correctly on the next tick, and b) if that threw an exception, it would not create a rejected promise.

**Comment by AprilArcus** [comment]
Thanks for your patience. One last question:

```JavaScript
function test() {
  return (
    (db.destroy && typeof db.destroy.then === 'function') :
    db.destroy ? Promise.resolve().then(function () { return db.destroy(); })
  ).then(function () {});
}
```

?

**Comment by AprilArcus** [comment]
Thanks, I think I understand correctly now :)
